language: ruby
rvm:
  - '2.1.9'
  - '2.2.10'
  - '2.5.0'
  - '2.6.0'
script: bundle install && bundle exec rake spec

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libgsl0-dev
